DISABLE_ERRORS_LINTERS:
  - ACTION_ACTIONLINT
  - DOCKERFILE_HADOLINT
  - REPOSITORY_CHECKOV
  - SPELL_CSPELL
  - REPOSITORY_TRIVY
  - REPOSITORY_KICS
  - SPELL_LYCHEE
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - REPOSITORY_GIT_DIFF
