proxy-dns: true
proxy-dns-port: 54
proxy-dns-address: 0.0.0.0
proxy-dns-upstream:
  - https://security.cloudflare-dns.com/dns-query
  - https://cloudflare-dns.com/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
